# Generated by Django 3.1.1 on 2024-04-25 20:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheeses', '0003_auto_20240305_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeses.cheese'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'cheese')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='i_rating',
        ),
    ]
